
Sigdat.
---------------------------------------------------------------

https://sigdat.org/events


https://www.aclweb.org/anthology/events/emnlp-2018/


https://www.aclweb.org/anthology/events/emnlp-2017/


https://www.aclweb.org/anthology/events/emnlp-2016/



https://www.aclweb.org/anthology/events/emnlp-2015/


Vedios.
---------------------------------------------------------------

https://sigdat.org/videos

LITERATURE ON NEURAL ARCHITECTURE SEARCH
---------------------------------------------------------------
https://www.automl.org/automl/literature-on-neural-architecture-search/



Spark NLP.
---------------------------------------------------------------

http://bit.ly/Spark_Summit_Video

NLP - Healthcare Case study.
---------------------------------------------------------------

Case study healthcare
---------------------------------------------------------------
http://bit.ly/JSL_Kaiser_Case_Study


Baidu research publications.
---------------------------------------------------------------
http://research.baidu.com/Publications?research%5B%5D=0&year=0
